import { NextResponse } from 'next/server';
import connectToDatabase from '@/lib/mongodb';
import Otp from '@/models/Otp';
import User from '@/models/User';
import jwt from 'jsonwebtoken';
import bcrypt from 'bcryptjs';

const JWT_SECRET = process.env.JWT_SECRET || 'super_secret_dev_key';

export async function POST(req: Request) {
  try {
    const body = await req.json();
    const { name, phone, email, otp, username, password } = body;

    if (!name || !phone || !email || !otp || !username || !password) {
      return NextResponse.json({ error: 'All fields are required.' }, { status: 400 });
    }

    await connectToDatabase();

    // 1. Verify OTP
    const validOtp = await Otp.findOne({
      email,
      otp,
      expiresAt: { $gt: new Date() }
    });

    if (!validOtp) {
      return NextResponse.json({ error: 'Invalid or expired OTP. Please request a new one.' }, { status: 401 });
    }

    // 2. Check if username is unique
    const existingUserByUsername = await User.findOne({ username });
    if (existingUserByUsername) {
      return NextResponse.json({ error: 'Username is already taken. Please choose another.' }, { status: 409 });
    }

    // 3. Check if email/phone is already registered
    const existingUser = await User.findOne({ $or: [{ email }, { phone }] });
    if (existingUser) {
      return NextResponse.json({ error: 'Email or phone is already registered.' }, { status: 409 });
    }

    // 4. Hash password
    const salt = await bcrypt.genSalt(10);
    const hashedPassword = await bcrypt.hash(password, salt);

    // 5. Create User (refId is auto-generated by the pre-save hook)
    const newUser = await User.create({
      name,
      phone,
      email,
      username,
      password: hashedPassword,
      role: 'FAN',
      wallet: { depositBalance: 0, winningsBalance: 0, bonusBalance: 100 }, // Give 100 bonus for joining
    });

    // 6. Delete OTP
    await Otp.deleteOne({ _id: validOtp._id });

    // 7. Generate JWT token
    const token = jwt.sign(
      { userId: newUser._id, role: newUser.role, email: newUser.email, username: newUser.username },
      JWT_SECRET,
      { expiresIn: '7d' }
    );

    // 8. Return response and set cookie
    const response = NextResponse.json({ 
      message: 'Registration successful',
      user: {
        id: newUser._id,
        refId: newUser.refId,
        username: newUser.username,
        name: newUser.name,
        phone: newUser.phone,
        role: newUser.role,
        wallet: newUser.wallet
      }
    });

    response.cookies.set('auth_token', token, {
      httpOnly: true,
      secure: process.env.NODE_ENV === 'production',
      sameSite: 'lax',
      maxAge: 7 * 24 * 60 * 60, // 7 days
      path: '/'
    });

    return response;

  } catch (error) {
    console.error('Registration Error:', error);
    return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
  }
}
